### ISSUE TITLE
How is the data preprocessing for the UI-PRMd dataset done?

### ISSUE THREAD

**Issue by CyWang-Jade** [fokhruli/STGCN-rehab#2]

**Comment by fokhruli** [comment]
Can you ask the question more specifically? Like the input dimension, time-steps or other elements?

**Comment by fokhruli** [comment]
For preprocessing of the UI-PRMD dataset, we strictly follow the UI-PRMD dataset author's [procedure](https://arxiv.org/abs/1901.10435). You can find their work [here](https://github.com/avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises). Also, we shared the whole preprocessed UI-PRMD dataset in our [github repository](https://github.com/fokhruli/STGCN-rehab).  Feel free to check it out. If you have any further questions, please let me know.

**Comment by CyWang-Jade** [comment]
> For preprocessing of the UI-PRMD dataset, we strictly follow the UI-PRMD dataset author's [procedure](https://arxiv.org/abs/1901.10435). You can find their work [here](https://github.com/avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises). Also, we shared the whole preprocessed UI-PRMD dataset in our [github repository](https://github.com/fokhruli/STGCN-rehab). Feel free to check it out. If you have any further questions, please let me know.

Thank you very much for your reply.My questions are as follows：

How to construct UI-PRMD human body topology map.
The dataset used by Liao et al is a reduced UI-PRMD, but the data you posted is unreduced. For example, there are only 70 correct actions and 70 incorrect actions in Liao's ex4. But in your posted data, ex4 has 90 sets of correct actions and 90 sets of wrong actions.
the score labels of your UI-PRMD datasets are also diffcult to separate, most of the wrong actions in ex4 are above 90 points, even higher than the correct actions.

**Comment by imuxwb** [comment]
I want to know where the self-attention was added, and the self-attention matrix graph, is it calculated using the bias matrix

**Comment by fokhruli** [comment]
Please check this [issue](https://github.com/fokhruli/STGCN-rehab/issues/7#issuecomment-2008652905).
