### ISSUE TITLE
Why use Standardnorm towards the y_label(score) and use the linear function as the activation in the final dense layer?

### ISSUE THREAD

**Issue by Ytang520** [fokhruli/STGCN-rehab#5]
I am puzzled by your use of Standard Normalization on the y_label (score), as well as the linear activation function in the final dense layer (as shown in the picture below). Given that this is a score prediction problem, and scores are limited to [0,1] on the UI-PRIMD dataset or [0,50] on the Kimore dataset, it is possible that the final predicted score could exceed these limits. Is there a reason for this implementation that I may have missed?

![Dense](https://user-images.githubusercontent.com/125520425/231914137-2f69bd28-d968-40e2-86eb-df1081e186a9.png)
![standardnorm](https://user-images.githubusercontent.com/125520425/231914149-4afb7047-4387-4e38-9d80-3587c1b70640.png)

**Comment by fokhruli** [comment]
Although the final predicted score could exceed the allowed limits, there are specific reasons why the implementation uses standard normalization on the y_label and linear activation function in the final dense layer. For instance, the normalization and activation functions help with numerical stability and ensure that the neural network can learn the complex relationships between the input features and the output scores.

Moreover, the unbounded and normalized output predictions can later be transformed to the allowed range, such as [0-50], before evaluation or deployment. This approach allows the neural network to learn from the entire range of data, not just the allowed range. Consequently, this can lead to better overall performance.

**Comment by fokhruli** [comment]
While it is possible that the final predicted score could exceed the allowed limits and lead to incorrect predictions, there are specific reasons why the implementation is set up this way. One possible reason is that the normalization and activation functions were used for numerical stability and to enable the neural network to learn complex relationships between the input features and output scores effectively. Additionally, the unbounded output predictions can be transformed to the allowed range (e.g., [0-50]) during evaluation or deployment. This approach enables the neural network to learn from the entire range of data, not just the allowed range, which can lead to better overall performance.
