### ISSUE TITLE
self_attention

### ISSUE THREAD

**Issue by imuxwb** [fokhruli/STGCN-rehab#7]
I want to know where the self-attention was added, and the self-attention matrix graph, is it calculated using the bias matrix

**Comment by fokhruli** [comment]
Self attention was calculated using convlstm network which calculate spatial and temopral attention of each joint. You can found the code description in [sgcn.py](https://github.com/fokhruli/STGCN-rehab/blob/0b13afb55c1cd2c238389c041e604cfb4ca2cec8/GCN/sgcn_lstm.py#L29C1-L47C55) file.
